# Generated by Django 5.2.4 on 2025-07-22 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_cognome_ragione_sociale', models.CharField(max_length=255)),
                ('codice_fiscale', models.CharField(blank=True, help_text='Valido sia per persone fisiche che giuridiche', max_length=16)),
                ('partita_iva', models.CharField(blank=True, max_length=11)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('cap', models.CharField(blank=True, max_length=5)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anagrafica',
                'verbose_name_plural': 'Tutte le Anagrafiche',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('anagrafica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.anagrafica')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
            bases=('core.anagrafica',),
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('anagrafica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.anagrafica')),
                ('mansione', models.CharField(max_length=255)),
                ('data_assunzione', models.DateField()),
                ('data_fine_rapporto', models.DateField(blank=True, null=True)),
                ('costo_orario', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('note_generali', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
            },
            bases=('core.anagrafica',),
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('anagrafica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.anagrafica')),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
            },
            bases=('core.anagrafica',),
        ),
    ]
