# Generated by Django 5.2.4 on 2025-07-22 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anagrafica_cliente_dipendente_fornitore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codice_cantiere', models.CharField(help_text='Un codice univoco per identificare il cantiere', max_length=20, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine_prevista', models.DateField(blank=True, null=True)),
                ('data_chiusura_effettiva', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('Bozza', 'Bozza'), ('Aperto', 'Aperto'), ('Sospeso', 'Sospeso'), ('Chiuso', 'Chiuso'), ('Annullato', 'Annullato')], default='Bozza', max_length=20)),
                ('cliente', models.ForeignKey(help_text='Il cliente a cui è associato il cantiere', on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cantiere',
                'verbose_name_plural': 'Cantieri',
                'ordering': ['-data_inizio'],
            },
        ),
    ]
