# Generated by Django 5.2.4 on 2025-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cantiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantiere',
            name='codice_cantiere',
            field=models.CharField(help_text='Es. C-2025-ROMA-001', max_length=50, unique=True),
        ),
    ]
