# Generated by Django 5.2.4 on 2025-07-22 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_alter_cantiere_codice_cantiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTestata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('FatturaVendita', 'Fattura di Vendita'), ('NotaCreditoVendita', 'Nota di Credito di Vendita'), ('FatturaAcquisto', 'Fattura di Acquisto'), ('NotaCreditoAcquisto', 'Nota di Credito di Acquisto')], max_length=30)),
                ('stato', models.CharField(choices=[('Bozza', 'Bozza'), ('Confermato', 'Confermato'), ('Annullato', 'Annullato')], default='Bozza', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('numero_documento', models.CharField(max_length=50)),
                ('data_documento', models.DateField()),
                ('imponibile', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('cantiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='core.cantiere')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'cliente')), models.Q(('app_label', 'core'), ('model', 'fornitore')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modalita_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.modalitapagamento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('quantita', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imponibile_riga', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('iva_riga', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('aliquota_iva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.aliquotaiva')),
                ('testata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='core.documentotestata')),
            ],
            options={
                'verbose_name': 'Riga Documento',
                'verbose_name_plural': 'Righe Documento',
            },
        ),
    ]
