# Generated by Django 5.2.4 on 2025-07-22 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_alter_cantiere_codice_cantiere_documentotestata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scadenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('tipo_scadenza', models.CharField(choices=[('Incasso', 'Incasso (da Cliente)'), ('Pagamento', 'Pagamento (a Fornitore)')], max_length=20)),
                ('stato', models.CharField(choices=[('Aperta', 'Aperta'), ('Parziale', 'Pagata Parzialmente'), ('Saldata', 'Saldata'), ('Annullata', 'Annullata')], default='Aperta', max_length=20)),
                ('data_scadenza', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importo_pagato', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='core.documentotestata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scadenza',
                'verbose_name_plural': 'Scadenze',
                'ordering': ['data_scadenza'],
            },
        ),
    ]
