# Generated by Django 5.2.4 on 2025-07-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contofinanziario_contooperativo_primanota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotestata',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
